// <auto-generated />
using System;
using HomePetCare.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomePetCare.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20220829000208_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HomePetCare.App.Dominio.Formula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Medicamento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Formulas");
                });

            modelBuilder.Entity("HomePetCare.App.Dominio.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnoNacimiento")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeuñoPerroId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoSalud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MedicoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReporteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeuñoPerroId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("ReporteId");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("HomePetCare.App.Dominio.PropietarioMascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PropietariosMascotas");
                });

            modelBuilder.Entity("HomePetCare.App.Dominio.Recomendaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recomendacion");
                });

            modelBuilder.Entity("HomePetCare.App.Dominio.ReporteVisita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EstadoDeAnimo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FechaVisita")
                        .HasColumnType("int");

                    b.Property<int?>("FormulasId")
                        .HasColumnType("int");

                    b.Property<int>("FrecuenciaCardiaca")
                        .HasColumnType("int");

                    b.Property<int>("FrecuenciaRespiratoria")
                        .HasColumnType("int");

                    b.Property<int?>("MedicoId")
                        .HasColumnType("int");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<int?>("RecomendacionId")
                        .HasColumnType("int");

                    b.Property<int>("Temperatura")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormulasId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("RecomendacionId");

                    b.ToTable("ReportesVisitas");
                });

            modelBuilder.Entity("HomePetCare.App.Dominio.VeterinarioDomiciliario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TarjetaProfesional")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VeterinariosDomiciliarios");
                });

            modelBuilder.Entity("HomePetCare.App.Dominio.Mascota", b =>
                {
                    b.HasOne("HomePetCare.App.Dominio.PropietarioMascota", "DeuñoPerro")
                        .WithMany()
                        .HasForeignKey("DeuñoPerroId");

                    b.HasOne("HomePetCare.App.Dominio.VeterinarioDomiciliario", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId");

                    b.HasOne("HomePetCare.App.Dominio.ReporteVisita", "Reporte")
                        .WithMany()
                        .HasForeignKey("ReporteId");

                    b.Navigation("DeuñoPerro");

                    b.Navigation("Medico");

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("HomePetCare.App.Dominio.ReporteVisita", b =>
                {
                    b.HasOne("HomePetCare.App.Dominio.Formula", "Formulas")
                        .WithMany()
                        .HasForeignKey("FormulasId");

                    b.HasOne("HomePetCare.App.Dominio.VeterinarioDomiciliario", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId");

                    b.HasOne("HomePetCare.App.Dominio.Recomendaciones", "Recomendacion")
                        .WithMany()
                        .HasForeignKey("RecomendacionId");

                    b.Navigation("Formulas");

                    b.Navigation("Medico");

                    b.Navigation("Recomendacion");
                });
#pragma warning restore 612, 618
        }
    }
}
